#PBS -N adj20
#PBS -o /home/eokpala/blm-research/scripts/user_analysis/logs/create_edge_list_out.txt
#PBS -e /home/eokpala/blm-research/scripts/user_analysis/logs/create_edge_list_err.txt
#PBS -l select=1:ncpus=16:ngpus=1:gpu_model=v100:mem=120gb:interconnect=hdr,walltime=72:00:00
#PBS -m abe
#PBS -M eokpala@clemson.edu

module add cuda/11.6.2-gcc/9.5.0 
module add cudnn/8.1.0.77-11.2-gcc/9.5.0 
module add anaconda3/2022.05-gcc/9.5.0

source activate blm-research-env

cd /home/eokpala/blm-research/scripts/user_analysis/
python create_edge_list.py
