#PBS -N preprocess
#PBS -o /home/eokpala/blm-research/scripts/logs/extract_preprocessed_parler_2020_out.txt
#PBS -e /home/eokpala/blm-research/scripts/logs/extract_preprocessed_parler_2020_err.txt
#PBS -l select=1:ncpus=16:ngpus=1:gpu_model=v100:mem=30gb:interconnect=hdr,walltime=72:00:00
#PBS -m abe
#PBS -M eokpala@clemson.edu

module add cuda/11.6.2-gcc/9.5.0 
module add cudnn/8.1.0.77-11.2-gcc/9.5.0 
module add anaconda3/2022.05-gcc/9.5.0

source activate blm-research-env

cd /home/eokpala/blm-research/scripts/
python preprocess.py
